config/routes.rb
Ifind5::Application.routes.draw do
  get "main/index"
  post "main/found"
  resources :sites

  root 'main#index'

  

end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  
  end

  def distance(site,lat,lng) 
  	Math.sqrt((site.lat - lat)**2 + (site.lon - lng)**2) 
  end
  def found
  	require 'geocoder'
  	address = params['street'] + ' ' + params['city'] + ' ' + params['state'] + ' ' + params['zip'] 
	where = Geocoder.search(address).first
	lat = where.geometry['location']['lat']
	lng = where.geometry['location']['lng']
	closest = Site.all.sort_by {|x| distance(x,lat,lng)}.take(3)
	google = Geocoder::Lookup::Google.new
	@listings = []
	closest.each do |close|
		miles = distance(close,lat,lng)	* 100
		map = google.map_link_url([close.lat, close.lon])
		@listings[@listings.size] = {'site' => close, 'miles' => miles, 'map' => map}
	end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :address, :city, :state, :zip, :phone, :contact, :url, :facebook, :twitter, :macs, :pcs, :sunday, :monday, :tuesday, :wedndesday, :thursday, :friday, :saturday, :holidays, :languages, :lat, :lon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ifind5</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/found.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

  <title>My Tasks</title>

  <!-- Bootstrap core CSS -->
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script> 
  <script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>

  <!-- Custom styles for this template -->
  <style>
  body {
    padding-top: 50px;
  }
  .starter-template {
    padding: 40px 15px;
    text-align: center;
  }
  </style>

  <script type="text/javascript">
$().ready(function() {
})
</script>
<!-- Just for debugging purposes. Don't actually copy this line! -->
<!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
    </head>

    <body>

      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Public Internet Finder</a>
            <ul class="nav nav-pills pull-right" style=''>
              <li class="active btn btn-sm" id='logout' 
              style='display:none'><a onclick='logout()' href="#">Logout</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

      <div style='display:none'>
        <button onclick='show_page(1)' type='button'>Show 1</button>
        <button onclick='show_page(2)' type='button'>Show 2</button>
        <button onclick='show_page(3)' type='button'>Show 3</button>
      </div>

      <div class="container" >
        <div class="well">
        	<div>
        	<p><% @listings.each do |listing |%>
        	<p><a href='<%= listing['map'] %>'><%= listing['site'].name %></a></p>
        	<p><%= listing['site'].address %></p>
        	<p><%= listing['site'].zip %></p>
        	<p><%= listing['miles'] %> miles</p>
        	<p>&nbsp;</p>
        	<% end %>	
        </div>
        </div>
      </div>
  </body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

  <title>My Tasks</title>

  <!-- Bootstrap core CSS -->
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script> 
  <script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>

  <!-- Custom styles for this template -->
  <style>
  body {
    padding-top: 50px;
  }
  .starter-template {
    padding: 40px 15px;
    text-align: center;
  }
  </style>

  <script type="text/javascript">
  $().ready(function() {
  })
  </script>
  <!-- Just for debugging purposes. Don't actually copy this line! -->
  <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
    </head>

    <body>

      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Public Internet Finder</a>
            <ul class="nav nav-pills pull-right" style=''>
              <li class="active btn btn-sm" id='logout' 
              style='display:none'><a onclick='logout()' href="#">Logout</a></li>
            </ul>
          </div><!--/.nav-collapse -->
          <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-right" role="form">
              <div class="form-group">
                <input type="text" placeholder="Email" class="form-control">
              </div>
              <div class="form-group">
                <input type="password" placeholder="Password" class="form-control">
              </div>
              <a class="btn btn-success" href='/sites'>Sign in</a>
            </form>
          </div><!--/.navbar-collapse -->
        </div>
      </div>
    </div>

    <div class="container" >
      <div class="row">
         <div class="span12" style='text-align:center'>
          <img width='800' src='LocalFreeWeb02colorWhiteBG.png'>
         </div>
      </div>
      <div class="well">
        <form role="form" method="POST" action="/main/found">
          <div class="form-group">
            <label for="street">Street Address</label>
            <input type="text" class="form-control" value="169 11th Street"
            id="street" name="street" placeholder="street address">
          </div>
          <div class="form-group">
            <label for="city">City</label>
            <input type="text" class="form-control" value="San Francisco"
            id="city" name="city" placeholder="city">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">State</label>
            <input type="text" class="form-control" value="California"
            id="state" name="state" placeholder="state">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">ZIP</label>
            <input type="text" class="form-control" value="94103"
            id="zip" name="zip" placeholder="zip">
          </div>
          <input name="authenticity_token" type="hidden" value="token_value">
          <button type="submit" onclick='login()' 
          class="btn btn-default">Search</button>
        </form>
      </div>
    </div>
  </body>
  </html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :macs %><br>
    <%= f.number_field :macs %>
  </div>
  <div class="field">
    <%= f.label :pcs %><br>
    <%= f.number_field :pcs %>
  </div>
  <div class="field">
    <%= f.label :sunday %><br>
    <%= f.text_field :sunday %>
  </div>
  <div class="field">
    <%= f.label :monday %><br>
    <%= f.text_field :monday %>
  </div>
  <div class="field">
    <%= f.label :tuesday %><br>
    <%= f.text_field :tuesday %>
  </div>
  <div class="field">
    <%= f.label :wedndesday %><br>
    <%= f.text_field :wedndesday %>
  </div>
  <div class="field">
    <%= f.label :thursday %><br>
    <%= f.text_field :thursday %>
  </div>
  <div class="field">
    <%= f.label :friday %><br>
    <%= f.text_field :friday %>
  </div>
  <div class="field">
    <%= f.label :saturday %><br>
    <%= f.text_field :saturday %>
  </div>
  <div class="field">
    <%= f.label :holidays %><br>
    <%= f.text_area :holidays %>
  </div>
  <div class="field">
    <%= f.label :languages %><br>
    <%= f.text_area :languages %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Contact</th>
      <th>Url</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th>Macs</th>
      <th>Pcs</th>
      <th>Sunday</th>
      <th>Monday</th>
      <th>Tuesday</th>
      <th>Wedndesday</th>
      <th>Thursday</th>
      <th>Friday</th>
      <th>Saturday</th>
      <th>Holidays</th>
      <th>Languages</th>
      <th>Lat</th>
      <th>Lon</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.name %></td>
        <td><%= site.address %></td>
        <td><%= site.city %></td>
        <td><%= site.state %></td>
        <td><%= site.zip %></td>
        <td><%= site.phone %></td>
        <td><%= site.contact %></td>
        <td><%= site.url %></td>
        <td><%= site.facebook %></td>
        <td><%= site.twitter %></td>
        <td><%= site.macs %></td>
        <td><%= site.pcs %></td>
        <td><%= site.sunday %></td>
        <td><%= site.monday %></td>
        <td><%= site.tuesday %></td>
        <td><%= site.wedndesday %></td>
        <td><%= site.thursday %></td>
        <td><%= site.friday %></td>
        <td><%= site.saturday %></td>
        <td><%= site.holidays %></td>
        <td><%= site.languages %></td>
        <td><%= site.lat %></td>
        <td><%= site.lon %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @site.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @site.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @site.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @site.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @site.phone %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @site.contact %>
</p>

<p>
  <strong>Url:</strong>
  <%= @site.url %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @site.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @site.twitter %>
</p>

<p>
  <strong>Macs:</strong>
  <%= @site.macs %>
</p>

<p>
  <strong>Pcs:</strong>
  <%= @site.pcs %>
</p>

<p>
  <strong>Sunday:</strong>
  <%= @site.sunday %>
</p>

<p>
  <strong>Monday:</strong>
  <%= @site.monday %>
</p>

<p>
  <strong>Tuesday:</strong>
  <%= @site.tuesday %>
</p>

<p>
  <strong>Wedndesday:</strong>
  <%= @site.wedndesday %>
</p>

<p>
  <strong>Thursday:</strong>
  <%= @site.thursday %>
</p>

<p>
  <strong>Friday:</strong>
  <%= @site.friday %>
</p>

<p>
  <strong>Saturday:</strong>
  <%= @site.saturday %>
</p>

<p>
  <strong>Holidays:</strong>
  <%= @site.holidays %>
</p>

<p>
  <strong>Languages:</strong>
  <%= @site.languages %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @site.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @site.lon %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>